### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by klannon** [jeffkinnison/shadho#18]
I was interested in checking out this tool, but when I found my way here I was disappointed to see that the documentation link seems to be broken.  Can it be updated or fixed?

![image](https://user-images.githubusercontent.com/5149849/98600765-12cbd680-22ac-11eb-83af-4c5340873f8d.png)

**Comment by jeffkinnison** [comment]
Ah, apologies, thanks for bringing this to my attention.

**Comment by jeffkinnison** [comment]
Okay, the docs are back up, however there are still issues so I'll close this and open a new enhancement issue to add to the docs.

For the time being, the examples should work, however this is a living project and things are subject to breaking despite my best efforts. If you run into any more problems, by all means submit a new ticket and I'll work on it!

**Comment by klannon** [comment]
I appreciate the quick action.  Thanks!
