### ISSUE TITLE
module shadho cannot be imported

### ISSUE THREAD

**Issue by tphung3** [jeffkinnison/shadho#19]
**Problem:** shadho module cannot be imported.
**How to reproduce:** (assuming that we have conda or miniconda)
```
conda create --name shadho-env
conda activate shadho-env
conda install pip
pip install shadho
python -c "import shadho"
```

The last command throws this error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/anaconda3/envs/shadho-env/lib/python3.9/site-packages/shadho/shadho.py", line 8, in <module>
    from .configuration import ShadhoConfig
ImportError: attempted relative import with no known parent package
```

It looks like an import error, which hopefully is easy to fix.

**Comment by jeffkinnison** [comment]
So I'm not able to recreate this issue, but I've [put in a fix that converts the relative imports to absolute imports](https://github.com/jeffkinnison/shadho/commit/c54175c8261c1926907e52a4ec7cdf90745db885).

**Comment by tphung3** [comment]
Thanks Jeff it works now.
